using FinanceTrackerAPI.Domain.Interfaces;
using FinanceTrackerAPI.Application.Interfaces;
using FinanceTrackerAPI.Application.Currencies.Queries.GetAllCurrencies;
using FinanceTrackerAPI.Application.Currencies.Queries.GetCurrencyById;
using FinanceTrackerAPI.Application.Currencies.Commands.UpdateCurrencyRate;
using FinanceTrackerAPI.Application.Users.Commands.LoginUser;
using FinanceTrackerAPI.Application.Users.Commands.RegisterUser;
using FinanceTrackerAPI.Application.Users.Commands.DeleteUser;
using FinanceTrackerAPI.Application.Users.Commands.ChangeEmail;
using FinanceTrackerAPI.Application.Users.Commands.ChangePassword;
using FinanceTrackerAPI.Application.Users.Queries.GetUserById;
using FinanceTrackerAPI.Application.Wallets.Commands.ChangeCurrency;
using FinanceTrackerAPI.Application.Wallets.Commands.ChangeIcon;
using FinanceTrackerAPI.Application.Wallets.Commands.ChangeNote;
using FinanceTrackerAPI.Application.Wallets.Commands.ChangeSortOrder;
using FinanceTrackerAPI.Application.Wallets.Commands.CreateWallet;
using FinanceTrackerAPI.Application.Wallets.Commands.DeleteWallet;
using FinanceTrackerAPI.Application.Wallets.Commands.RenameWallet;
using FinanceTrackerAPI.Application.Wallets.Queries.GetWalletById;
using FinanceTrackerAPI.Application.Wallets.Queries.GetWalletsByProfileId;
using FinanceTrackerAPI.Application.Profiles.Commands.CreateProfile;
using FinanceTrackerAPI.Application.Profiles.Commands.DeleteProfile;
using FinanceTrackerAPI.Application.Profiles.Commands.RenameProfile;
using FinanceTrackerAPI.Application.Profiles.Commands.ToggleProfileActive;
using FinanceTrackerAPI.Application.Profiles.Queries.GetProfileById;
using FinanceTrackerAPI.Application.Profiles.Queries.GetProfilesByUserId;
using FinanceTrackerAPI.Application.Units.Commands.CreateUnit;
using FinanceTrackerAPI.Application.Units.Commands.DeleteUnit;
using FinanceTrackerAPI.Application.Units.Commands.RenameUnit;
using FinanceTrackerAPI.Application.Units.Queries.GetAllUnits;
using FinanceTrackerAPI.Application.Units.Queries.GetUnitsByProfileId;
using FinanceTrackerAPI.Application.Credits.Commands.CreateCredit;
using FinanceTrackerAPI.Application.Credits.Commands.DeleteCredit;
using FinanceTrackerAPI.Application.Credits.Commands.RenameCredit;
using FinanceTrackerAPI.Application.Credits.Commands.MakePayment;
using FinanceTrackerAPI.Application.Credits.Commands.CloseCredit;
using FinanceTrackerAPI.Application.Credits.Queries.GetCreditById;
using FinanceTrackerAPI.Application.Credits.Queries.GetCreditsByProfileId;
using FinanceTrackerAPI.Application.Debts.Commands.CreateDebt;
using FinanceTrackerAPI.Application.Debts.Commands.DeleteDebt;
using FinanceTrackerAPI.Application.Debts.Commands.RenameCreditor;
using FinanceTrackerAPI.Application.Debts.Commands.MakePayment;
using FinanceTrackerAPI.Application.Debts.Commands.ChangeDueDate;
using FinanceTrackerAPI.Application.Debts.Commands.RepayDebt;
using FinanceTrackerAPI.Application.Debts.Queries.GetDebtById;
using FinanceTrackerAPI.Application.Debts.Queries.GetDebtsByProfileId;
using FinanceTrackerAPI.Application.Deposits.Commands.CreateDeposit;
using FinanceTrackerAPI.Application.Deposits.Commands.DeleteDeposit;
using FinanceTrackerAPI.Application.Deposits.Commands.RenameDeposit;
using FinanceTrackerAPI.Application.Deposits.Commands.TopUpDeposit;
using FinanceTrackerAPI.Application.Deposits.Commands.CloseDeposit;
using FinanceTrackerAPI.Application.Deposits.Queries.GetDepositById;
using FinanceTrackerAPI.Application.Deposits.Queries.GetDepositsByProfileId;
using FinanceTrackerAPI.Application.Categories.Commands.CreateCategory;
using FinanceTrackerAPI.Application.Categories.Commands.CreateSystemCategory;
using FinanceTrackerAPI.Application.Categories.Commands.DeleteCategory;
using FinanceTrackerAPI.Application.Categories.Commands.RenameCategory;
using FinanceTrackerAPI.Application.Categories.Commands.ChangeIcon;
using FinanceTrackerAPI.Application.Categories.Queries.GetCategoryById;
using FinanceTrackerAPI.Application.Categories.Queries.GetCategoriesByProfileId;
using FinanceTrackerAPI.Application.Categories.Queries.GetSystemCategories;
using FinanceTrackerAPI.Application.Transactions.Commands.CreateTransaction;
using FinanceTrackerAPI.Application.Transactions.Commands.DeleteTransaction;
using FinanceTrackerAPI.Application.Transactions.Commands.ChangeDescription;
using FinanceTrackerAPI.Application.Transactions.Commands.ChangeCategory;
using FinanceTrackerAPI.Application.Transactions.Queries.GetTransactionById;
using FinanceTrackerAPI.Application.Transactions.Queries.GetTransactionsByWalletId;
using FinanceTrackerAPI.Application.Transactions.Queries.GetWalletBalance;
using FinanceTrackerAPI.Application.RecurringTransactions.Commands.CreateRecurringTransaction;
using FinanceTrackerAPI.Application.RecurringTransactions.Commands.DeleteRecurringTransaction;
using FinanceTrackerAPI.Application.RecurringTransactions.Commands.DeactivateRecurringTransaction;
using FinanceTrackerAPI.Application.RecurringTransactions.Queries.GetRecurringTransactionById;
using FinanceTrackerAPI.Application.RecurringTransactions.Queries.GetRecurringTransactionsByWalletId;
using FinanceTrackerAPI.Infrastructure.Persistence;
using FinanceTrackerAPI.Infrastructure.Persistence.Repositories;
using FinanceTrackerAPI.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;

namespace FinanceTrackerAPI.API.Extensions;

public static class ServiceCollectionExtensions
{
  public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
  {
    services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(configuration.GetConnectionString("DefaultConnection")));
    services.AddScoped<IUserRepository, UserRepository>();
    services.AddScoped<IProfileRepository, ProfileRepository>();
    services.AddScoped<IWalletRepository, WalletRepository>();
    services.AddScoped<ICurrencyRepository, CurrencyRepository>();
    services.AddScoped<IUnitRepository, UnitRepository>();
    services.AddScoped<ICreditRepository, CreditRepository>();
    services.AddScoped<IDebtRepository, DebtRepository>();
    services.AddScoped<IDepositRepository, DepositRepository>();
    services.AddScoped<ICategoryRepository, CategoryRepository>();
    services.AddScoped<ITransactionRepository, TransactionRepository>();
    services.AddScoped<IRecurringTransactionRepository, RecurringTransactionRepository>();

    services.AddScoped<IPasswordHasher, PasswordHasher>();
    services.AddScoped<IJwtTokenGenerator, JwtTokenGenerator>();

    return services;
  }
  public static IServiceCollection AddApplication(this IServiceCollection services)
  {
    services.AddScoped<GetAllCurrenciesQueryHandler>();
    services.AddScoped<GetCurrencyByIdQueryHandler>();
    services.AddScoped<UpdateCurrencyRateCommandHandler>();
    services.AddScoped<RegisterUserCommandHandler>();
    services.AddScoped<LoginUserCommandHandler>();
    services.AddScoped<DeleteUserCommandHandler>();
    services.AddScoped<ChangeEmailCommandHandler>();
    services.AddScoped<ChangePasswordCommandHandler>();
    services.AddScoped<GetUserByIdQueryHandler>();
    services.AddScoped<CreateProfileCommandHandler>();
    services.AddScoped<DeleteProfileCommandHandler>();
    services.AddScoped<RenameProfileCommandHandler>();
    services.AddScoped<ToggleProfileActiveCommandHandler>();
    services.AddScoped<GetProfileByIdQueryHandler>();
    services.AddScoped<GetProfilesByUserIdQueryHandler>();
    services.AddScoped<CreateWalletCommandHandler>();
    services.AddScoped<DeleteWalletCommandHandler>();
    services.AddScoped<RenameWalletCommandHandler>();
    services.AddScoped<ChangeSortOrderCommandHandler>();
    services.AddScoped<ChangeIconCommandHandler>();
    services.AddScoped<ChangeCurrencyCommandHandler>();
    services.AddScoped<ChangeNoteCommandHandler>();
    services.AddScoped<GetWalletByIdQueryHandler>();
    services.AddScoped<GetWalletsByProfileIdQueryHandler>();
    services.AddScoped<CreateUnitCommandHandler>();
    services.AddScoped<DeleteUnitCommandHandler>();
    services.AddScoped<RenameUnitCommandHandler>();
    services.AddScoped<GetAllUnitsQueryHandler>();
    services.AddScoped<GetUnitsByProfileIdQueryHandler>();
    services.AddScoped<CreateCreditCommandHandler>();
    services.AddScoped<DeleteCreditCommandHandler>();
    services.AddScoped<RenameCreditCommandHandler>();
    services.AddScoped<MakePaymentCommandHandler>();
    services.AddScoped<CloseCreditCommandHandler>();
    services.AddScoped<GetCreditByIdQueryHandler>();
    services.AddScoped<GetCreditsByProfileIdQueryHandler>();
    services.AddScoped<CreateDebtCommandHandler>();
    services.AddScoped<DeleteDebtCommandHandler>();
    services.AddScoped<RenameCreditorCommandHandler>();
    services.AddScoped<MakeDebtPaymentCommandHandler>();
    services.AddScoped<ChangeDueDateCommandHandler>();
    services.AddScoped<RepayDebtCommandHandler>();
    services.AddScoped<GetDebtByIdQueryHandler>();
    services.AddScoped<GetDebtsByProfileIdQueryHandler>();
    services.AddScoped<CreateDepositCommandHandler>();
    services.AddScoped<DeleteDepositCommandHandler>();
    services.AddScoped<RenameDepositCommandHandler>();
    services.AddScoped<TopUpDepositCommandHandler>();
    services.AddScoped<CloseDepositCommandHandler>();
    services.AddScoped<GetDepositByIdQueryHandler>();
    services.AddScoped<GetDepositsByProfileIdQueryHandler>();
    services.AddScoped<CreateCategoryCommandHandler>();
    services.AddScoped<CreateSystemCategoryCommandHandler>();
    services.AddScoped<DeleteCategoryCommandHandler>();
    services.AddScoped<RenameCategoryCommandHandler>();
    services.AddScoped<ChangeIconCategoryCommandHandler>();
    services.AddScoped<GetCategoryByIdQueryHandler>();
    services.AddScoped<GetCategoriesByProfileIdQueryHandler>();
    services.AddScoped<GetSystemCategoriesQueryHandler>();
    services.AddScoped<CreateTransactionCommandHandler>();
    services.AddScoped<DeleteTransactionCommandHandler>();
    services.AddScoped<ChangeDescriptionCommandHandler>();
    services.AddScoped<ChangeCategoryTransactionCommandHandler>();
    services.AddScoped<GetTransactionByIdQueryHandler>();
    services.AddScoped<GetTransactionsByWalletIdQueryHandler>();
    services.AddScoped<GetWalletBalanceQueryHandler>();
    services.AddScoped<CreateRecurringTransactionCommandHandler>();
    services.AddScoped<DeleteRecurringTransactionCommandHandler>();
    services.AddScoped<DeactivateRecurringTransactionCommandHandler>();
    services.AddScoped<GetRecurringTransactionByIdQueryHandler>();
    services.AddScoped<GetRecurringTransactionsByWalletIdQueryHandler>();
    return services;
  }
}